#!/usr/bin/env bash
# display information about subdomains.

if [ $# -lt 1 ] || [ $# -gt 2 ];then
    echo "Usage: 0-world_wide_web <domain> <subdomain (optional)>"
fi

DOM="$1"
SUB_DOMS=("www" "lb-01" "web-01" "web-02")

if [ $# -eq 1 ]; then
    for SUB in "${SUB_DOMS[@]}"; do
	TYPE=$(dig "$DOM" | awk '/ANSWER SECTION/{getline; print $4}')
	VALUE=$(dig "$DOM" | awk '/ANSWER SECTION/{getline; print $5}')
	echo "The subdomain $SUB is a $TYPE recored and points to $VALUE"
    done

elif [ $# -eq 2 ]; then
    SUB="$2"
    TYPE=$(dig "$SUB.$DOM" | awk '/ANSWER SECTION/{getline; print $4}')
    VALUE=$(dig "$SUB.$DOM" | awk '/ANSWER SECTION/{getline; print $5}')
    echo "The subdomain $SUB is a $TYPE recored and points to $VALUE"
fi
