#!/usr/bin/env bash
# transfers a file from a client to a server.

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file="$1"
ip="$2"
username="$3"

if [ $# -eq 3 ]; then
    scp -o StrictHostKeyChecking=no "$file" "$username"@"$ip":~/
else
    ssh_key_file="$4"
    scp -o StrictHostKeyChecking=no -i "$ssh_key_file" "$file" "$username"@"$ip":~/
fi
