#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

# Add a new directive to the default Nginx file for redirecting the page /redirect_me
new_location="\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com;\n\t}\n\n\tlocation / {"

sudo sed -i "s#^\s*location / {# $new_location#" /etc/nginx/sites-available/default

# Restart Nginx server
sudo service nginx restart
