#!/usr/bin/env bash
# Install nginx web server

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Allow connections to Nginx over the firwall
sudo ufw allow 'Nginx HTTP'

# Cretae the index.html file
sudo bash -c 'echo -e "Hello World!" > /var/www/html/index.html'

# Configure Nginx to listen on port 80
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
       listen 80 default_server;
       listen [::]:80 default_server;

       root /var/www/html;
       index index.html;

       server_name _;

       location / {
                try_files \$uri \$uri/ =404;
       }

       location /redirect_me {
       		return 301 https://youtube.com;
       }
}
EOF'

# Restart Nginx
sudo service nginx restart
