#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

# Define the redirection confuguration
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/redirect_me
    server {
    	   listen 80;
	   server_name aksaim.tech;

	   location /redirect_me {
	   	    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	   }
    }
EOF'

# Enable the redirection site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx server
sudo service nginx restart
