#!/usr/bin/env bash
# Install nginx web server

# Install Nginx
echo "############## Installing Nginx ##############"
sudo apt-get update
sudo apt-get install -y nginx

echo "############## Configuring the Nginx server ##############"

# Allow connections to Nginx over the firewall
sudo ufw allow 'Nginx FULL'

# Create the index page
sudo bash -c 'echo -e "Hello World!" > /var/www/html/index.html'

# Create a custom 404 erorr page
sudo bash -c 'echo "Ceci n'\''est pas une page" > /var/www/html/404.html'

# Configur Nginx to listen on port 80
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
       listen 80 default_server;
       listen [::]:80 default_server;

       root /var/www/html;
       index index.html;

       server_name _;

       location /redirect_me {
                return 301 https://youtube.com;
       }

       location / {
                try_files \$uri \$uri/ =404;
       }

error_page 404 /404.html;
       location = /404.html {
                root /var/www/html;
                internal;
       }
}
EOF'

echo "############## Restarting Nginx Serevr ##############"
sudo service nginx restart

echo "############## Done server is ready ##############"
