#!/usr/bin/env bash
# Install and configure HAproxy on a load balnce server.

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 4096
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 391265-web-01 54.85.96.8:80 check
    server 391265-web-02 18.214.88.174:80 check
EOF'

# Enable haproxy to be started by init script
sudo bash -c 'echo -e "# Enable the HAProxy init script\nENABLED=1" >> /etc/default/haproxy'

# Restart HAProxy
sudo service haproxy restart
sudo service haproxy start
