#!/usr/bin/env bash
# Create a backup for sql server using the user root

if [ $# -ne 1 ]; then
   echo "Usage: $0 <mysql root password>"
   exit 1
fi

MYSQL_ROOT_PASSWORD=$1
DATE=$(date +"%d-%m-%Y")
DUMP_FILE="backup.sql"
ARCHIVE_NAME="${DATE}.tar.gz"


# create the backup file
mysqldump -uroot -p"$MYSQL_ROOT_PASSWORD" --all-databases > "$DUMP_FILE"

# Archive the backup file
tar -czvf "$ARCHIVE_NAME" "$DUMP_FILE"
