#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
