#!/usr/bin/env bash
# manage the file manage_my_process

if [ $# -eq 1 ]; then
    if [[ $1 != "start" && $1 != "stop" && $1 != "restart" ]]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
    exit
fi

case "$1" in
    start)
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
	;;

    stop)
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;

    restart)
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
esac
