#!/usr/bin/env bash
# displays To infinity and beyond indefinitely and trap the SIGTERM signal to print I am invincible!!!.

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
