#!/usr/bin/env bash
# read from the file /etc/passwd
#and only display:
#    username
#    user id
#    Home directory path for the user

while IFS=":" read -r username password id group info home shell
do

    echo "The user $username is part of the $group gang, lives in $home and rides $shell. $id's place is protected by the passcode $password, more info about the user here: $info"

done < /etc/passwd
