#!/usr/bin/env bash
# displays Best School 10 times using while loop and diplay hi in the 9th iteration

i=1

while [ $i -lt 21 ]
do
    case $i in
	4) echo $i; echo "bad luck from China";;
	9) echo $i; echo "bad luck from Japan";;
	17) echo $i; echo "bad luck from Italy";;
	*) echo $i;;
    esac
    i=$((i + 1))
done
