#!/usr/bin/env bash
# displays Best School 10 times using while loop and diplay hi in the 9th iteration

i=1

while [ $i -lt 21 ]
do
    echo $i

    if [ $i -eq 4 ]
    then
	echo "bad luck from China"
    elif [ $i -eq 9 ]
    then
	echo "bad luck from Japan"
    elif [ $i -eq 17 ]
    then
	echo "bad luck from Italy"
    fi

    i=$((i + 1))
done
