#!/usr/bin/bash

# Install ufw if not already installed
sudo apt update
sudo apt install -y ufw

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw with automatic confirmation
echo "y" | sudo ufw enable

# Check ufw status
sudo ufw status verbose
