#!/usr/bin/env bash
# onfigures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

#Copy the content of the hostes file to a new file
cp /etc/hosts ~/new_hosts

sed -i 's/^[0-9.]\+\tlocalhost$/127.0.0.2\tlocalhost/' ~/new_hosts
echo -e "8.8.8.8\tfacebook" >> ~/new_hosts
cp -f ~/new_hosts /etc/hosts
