#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
