#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user

# Update the nginx config file
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Stop apache2
sudo service apache2 stop
sudo kill apache2

# Restart nginx
sudo -u nginx service nginx restart
